// Generated by Wyre compiler 0.1.0

module top(
	input clk,
	input button,
	output reg [2:0] leds = 0
);

wire [2:0] inc_0_o;

always @(posedge clk) begin
	if (button) begin
		leds <= 3'd7;
	end else begin
		leds <= inc_0_o;
	end
end

(* keep *) inc_0 inc_0(
	.a(leds),
	.o(inc_0_o)
);

endmodule

module inc_0(
	input [2:0] a,
	output [2:0] o
);

assign o = (a) + (1);

endmodule
